# Generated by Django 4.1.5 on 2023-01-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
